### ISSUE TITLE
Operation not permitted at startup

### ISSUE THREAD

**Issue by kverkind** [d8ahazard/FlexConnect#1]
EBUG:FlexConnect:Cast length is 1
DEBUG:FlexConnect:Item count is 1
DEBUG:FlexConnect:Diffs are 1560284877.9619982 and 1560285512.5405037 and 634.5785055160522.
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "FlexConnect.py", line 2842, in socket_spy
    sniff(filter='tcp or udp', prn=custom_action)
  File "./lib/scapy/sendrecv.py", line 731, in sniff
    *arg, **karg)] = iface
  File "./lib/scapy/arch/linux.py", line 567, in __init__
    self.ins = socket.socket(socket.AF_PACKET, socket.SOCK_RAW, socket.htons(type))
  File "/usr/lib/python3.5/socket.py", line 134, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
PermissionError: [Errno 1] Operation not permitted

**Comment by kverkind** [comment]
Project not maintained
